"""Generate a readable MARKDOWN report of the prompt-format ablation: for each scenario it embeds the
input frames, then for each prompt config shows the exact SYSTEM + INSTRUCTION + the model's OUTPUT.
Reuses the scenarios/configs/prompt-builder from benchmark_prompts.py.

Run: env -u VIRTUAL_ENV -u PYTHONPATH PYTHONPATH=. QWEN=Qwen/Qwen3.5-2B \
        .venv/bin/python planner_poc/gen_prompt_bench_md.py
Out: docs/prompt_bench/PROMPT_BENCH.md  (+ frames in docs/prompt_bench/frames/)
"""
import os
import sys

import torch

import os; REPO = os.environ.get("NITROGEN_REPO", "/home/t-nagupta/NitroGen-With-VLM-Planning")
sys.path.insert(0, REPO); sys.path.insert(0, REPO + "/planner_poc")
import benchmark_prompts as B
from nitrogen.planner import PlanEncoder, PlannerConfig

OUT_DIR = REPO + "/docs/prompt_bench"
FRAMES_REL = "frames"   # frames live in docs/prompt_bench/frames/, referenced relatively from the md
CFG_TITLE = {
    "C0_base": "C0 — base (no extras)",
    "C1_controls": "C1 — +controls (control scheme in system prompt)",
    "C2_history": "C2 — +history (dump of the agent's own actions between frames)",
    "C3_grounded": "C3 — +grounded (use concrete control terms, not vague 'forward'/'explore')",
    "C4_all": "C4 — +all (controls + history + grounded)",
}
SCEN_NOTE = {
    "platformer_progress": "The hero is advancing right and jumping onto ledges — things are going well.",
    "platformer_BLOCKED": "REAL stuck moment (from the thextech rollout, state-verified): the hero is "
                          "jammed at the base of the central pillar — it held RIGHT but its x-position "
                          "stayed frozen at 424. To get onto the platform it must JUMP, not keep "
                          "pushing RIGHT.",
    "topdown_BLOCKED": "The hero held DOWN into a wall and isn't progressing — it should try another "
                       "direction.",
    "racing_STRAIGHT": "The kart is centred on a straight, doing well — the move is to keep going "
                       "(ACCELERATE), and a good plan should say so concretely.",
}
# map each scenario's frame globs -> the copied report frames
def md_escape(s):
    return s.replace("|", "\\|").replace("\n", " ⏎ ")


def main():
    pl = PlanEncoder(PlannerConfig(backbone_name_or_path=B.QWEN)); pl.load()
    dev = "cuda"
    if next(pl.backbone.parameters()).device != torch.device(dev):
        pl.backbone.to(dev)

    lines = [
        "# Prompt-format ablation — frozen Qwen3.5-2B planner",
        "",
        "How far does **pure prompting / input-format** (no training) get the System-2 planner on real "
        "game frames? Each scenario below shows the **input frames**, then for five prompt configs the "
        "**exact system prompt**, the **instruction**, and the **model's output**.",
        "",
        "Knobs: **+controls** (tell it the control scheme) · **+history** (dump the agent's OWN "
        "actions taken between the frames — no privileged game state) · **+grounded** (nudge it to use "
        "concrete control/game-specific terms so the direction is unambiguous, e.g. \"move RIGHT\" "
        "instead of \"move forward\").",
        "",
        "_Generated by `planner_poc/gen_prompt_bench_md.py` (frames in `frames/`)._",
        "",
        "---",
        "",
    ]

    for name, genre, globs, history, typ in B.CASES:
        frames = B.imgs(globs)
        lines.append(f"## {name}  ·  _{genre}, {len(frames)} frames, type={typ}_")
        lines.append("")
        lines.append(f"> {SCEN_NOTE.get(name, '')}")
        lines.append("")
        # embed frames (oldest -> newest). dedup repeated frame (e.g. BLOCKED uses one frame x3).
        seen = []
        for g in globs:
            if g not in seen and os.path.exists(os.path.join(OUT_DIR, FRAMES_REL, g)):
                seen.append(g)
        imgs_md = " ".join(f'<img src="{FRAMES_REL}/{g}" width="240">' for g in seen)
        lines.append(imgs_md)
        lines.append("")
        lines.append(f"**Action-history dump** (used by +history / +all): `{history}`")
        lines.append("")
        for cfg in B.CONFIGS:
            sys_p, instr = B.build_prompt(cfg, genre, history)
            plan = pl.generate_plan(frames, dev, instruction=instr, system=sys_p, max_new_tokens=48)
            lines.append(f"### {CFG_TITLE[cfg]}")
            lines.append("")
            lines.append(f"- **System:** {md_escape(sys_p)}")
            lines.append(f"- **Instruction:** {md_escape(instr)}")
            lines.append(f"- **Output:** `{md_escape(plan)}`")
            lines.append("")
            print(f"  {name}/{cfg}: {plan[:70]!r}", flush=True)
        lines.append("---")
        lines.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "PROMPT_BENCH.md")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nwrote {path}")


if __name__ == "__main__":
    main()
